### ISSUE TITLE
e_Fatal undefined as of Ghostscript 9.18

### ISSUE THREAD

**Issue by antonva** [MrSaints/go-ghostscript#1]
There were some changes to the Ghostscript errors in v 9.18. These are not regressions or a bug. C.e_Fatal does not exist anymore.

```
 # github.com/mrsaints/go-ghostscript/ghostscript
could not determine kind of name for C.e_Fatal
```

As per the bug report on the gs-bugs mailing list ([here](https://ghostscript.com/pipermail/gs-bugs/2015-November/042447.html)) this can be hotfixed by defining `e_Fatal` as `gs_error_Fatal`in the CGO preamble like so:
```
...
#define e_Fatal gs_error_Fatal
*/
import "C"
```

**Comment by antonva** [comment]
Nevermind, saw the version restrictions when I went through the rest of the code. Closing this.

**Comment by MrSaints** [comment]
We should probably update it.

**Comment by MrSaints** [comment]
Resolved I believe.
