### ISSUE TITLE
Ghostscript interpreter version not supported: 926 (must be >910, and <915)

### ISSUE THREAD

**Issue by opvexe** [MrSaints/go-ghostscript#2]
2020/01/08 19:54:29 Revision: {Product:GPL Ghostscript Copyright:Copyright (C) 2018 Artifex Software, Inc.  All rights reserved. Revision:926 RevisionDate:20181120}
panic: Ghostscript interpreter version not supported: 926 (must be >910, and <915)

**Comment by opvexe** [comment]
/*
#include <stdlib.h>
#include <ghostscript/gdevdsp.h>
#include <ghostscript/iapi.h>
#include <ghostscript/ierrors.h>
#cgo LDFLAGS: -lgs
#define e_Fatal gs_error_Fatal
*/
import "C"

import (
	"fmt"
	"sync"
	"unsafe"
)

const (
	MAX_SUPPORTED_REVISION = 926
	MIN_SUPPORTED_REVISION = 910
	GS_NO_ERRORS           = 0
	GS_FATAL_ERROR         = C.e_Fatal
)

**Comment by MrSaints** [comment]
Related to #1. I've yet to try it on newer versions. Happy to accept an MR.

**Comment by opvexe** [comment]
> Related to #1. I've yet to try it on newer versions. Happy to accept an MR.

thank you ,i have sovle this problem
